import { assertValidDielineGraph } from "../validation/validateDielineGraph";
import { assembleGraphFromContext } from "./graphAssembler";
import { getPartContractForRecipePart, getPartRegistration, partRegistry } from "./partRegistry";
import { evaluateRecipeConstraints, resolveNumberExpression, resolveRecipeParameters } from "./formulaResolver";
import {
  contractWarnings,
  issueMessages,
  throwIfValidationErrors,
  validatePartAttachTarget,
  validatePartResultAgainstContract,
} from "./partContractValidator";
import { validateRecipe } from "./validateRecipe";
import type {
  Anchor,
  ComponentLayoutContext,
  ComponentRecipePart,
  ComponentEngineDebugResult,
  DielineComponentRecipe,
  PartResult,
} from "./types";
import type { DielineGraph, ParameterValueMap } from "../types";

export function generateFromRecipe(
  recipe: DielineComponentRecipe,
  userValues: Record<string, unknown> = {},
): DielineGraph {
  return generateFromRecipeDebug(recipe, userValues).graph;
}

export function generateFromRecipeDebug(
  recipe: DielineComponentRecipe,
  userValues: Record<string, unknown> = {},
): ComponentEngineDebugResult {
  const recipeValidation = validateRecipe(recipe, partRegistry);

  const resolved = resolveRecipeParameters(recipe, userValues);
  const constraints = evaluateRecipeConstraints(recipe, resolved.values);
  if (constraints.errors.length > 0) {
    throw new Error(`${recipe.label ?? recipe.id} constraints failed: ${constraints.errors.join("; ")}`);
  }

  const ctx = createLayoutContext(recipe, resolved.values);
  ctx.warnings.push(...recipeValidation.warnings);
  ctx.warnings.push(...resolved.warnings);
  ctx.warnings.push(...constraints.warnings);

  for (const partConfig of recipe.parts) {
    const registration = getPartRegistration(partConfig.type);
    const contract = getPartContractForRecipePart(partConfig, registration);
    const attachIssues = validatePartAttachTarget(ctx, partConfig, contract);
    throwIfValidationErrors(attachIssues, `Part ${partConfig.id} failed contract target validation`);
    ctx.warnings.push(...issueMessages(attachIssues, "warning"));
    ctx.warnings.push(...issueMessages(contractWarnings(partConfig, contract), "warning"));

    const result = registration.implementation.build(ctx, partConfig as ComponentRecipePart);
    const outputIssues = validatePartResultAgainstContract(partConfig, registration, contract, result);
    throwIfValidationErrors(outputIssues, `Part ${partConfig.id} failed contract output validation`);
    ctx.warnings.push(...issueMessages(outputIssues, "warning"));
    ctx.addPartResult(partConfig.id, result);
  }

  const { graph } = assembleGraphFromContext({
    recipe,
    params: ctx.params,
    parameterSpecs: resolved.parameterSpecs,
    faces: ctx.faces,
    creases: ctx.creases,
    geometry: ctx.geometry,
    parts: ctx.parts,
    faceTreeHints: ctx.faceTreeHints,
    warnings: ctx.warnings,
  });

  assertValidDielineGraph(graph, recipe.label ?? recipe.id);
  return {
    graph,
    anchors: Array.from(ctx.anchors.values()),
    warnings: ctx.warnings,
  };
}

function createLayoutContext(recipe: DielineComponentRecipe, params: ParameterValueMap): ComponentLayoutContext {
  const ctx: ComponentLayoutContext = {
    recipe,
    params,
    faces: [],
    creases: [],
    geometry: [],
    anchors: new Map<string, Anchor>(),
    parts: [],
    faceTreeHints: [],
    warnings: [],
    getAnchor(anchorId: string): Anchor {
      const anchor = ctx.anchors.get(anchorId);
      if (!anchor) {
        throw new Error(`Missing anchor: ${anchorId}`);
      }
      return anchor;
    },
    numberValue(value: unknown, label: string): number {
      return resolveNumberExpression(value, ctx.params, label);
    },
    addPartResult(partId: string, result: PartResult) {
      for (const face of result.faces ?? []) {
        if (ctx.faces.some((candidate) => candidate.id === face.id)) {
          throw new Error(`Duplicate face id generated by part ${partId}: ${face.id}`);
        }
        ctx.faces.push(face);
      }

      for (const crease of result.structuralCreases ?? []) {
        if (ctx.creases.some((candidate) => candidate.id === crease.id)) {
          throw new Error(`Duplicate crease id generated by part ${partId}: ${crease.id}`);
        }
        ctx.creases.push(crease);
      }

      for (const primitive of result.geometry ?? []) {
        if (ctx.geometry.some((candidate) => candidate.id === primitive.id)) {
          throw new Error(`Duplicate geometry primitive id generated by part ${partId}: ${primitive.id}`);
        }
        ctx.geometry.push(primitive);
      }
      ctx.faceTreeHints.push(...(result.faceTreeHints ?? []));
      ctx.warnings.push(...(result.warnings ?? []));

      for (const anchor of result.anchors ?? []) {
        if (ctx.anchors.has(anchor.id)) {
          throw new Error(`Duplicate anchor id generated by part ${partId}: ${anchor.id}`);
        }
        ctx.anchors.set(anchor.id, anchor);
      }

      if (result.part) {
        if (ctx.parts.some((candidate) => candidate.id === result.part?.id)) {
          throw new Error(`Duplicate part id generated by part ${partId}: ${result.part.id}`);
        }
        ctx.parts.push(result.part);
      }
    },
  };

  return ctx;
}
