import { assertValidDielineGraph } from "../validation/validateDielineGraph";
import { assembleGraphFromContext } from "./graphAssembler";
import { getPartGenerator, partRegistry } from "./partRegistry";
import { resolveNumberExpression, resolveRecipeParameters } from "./formulaResolver";
import { validateRecipe } from "./validateRecipe";
import type {
  Anchor,
  ComponentLayoutContext,
  ComponentRecipePart,
  DielineComponentRecipe,
  PartResult,
} from "./types";
import type { DielineGraph, ParameterValueMap } from "../types";

export function generateFromRecipe(
  recipe: DielineComponentRecipe,
  userValues: Record<string, unknown> = {},
): DielineGraph {
  validateRecipe(recipe, partRegistry);

  const resolved = resolveRecipeParameters(recipe, userValues);
  const ctx = createLayoutContext(recipe, resolved.values);
  ctx.warnings.push(...resolved.warnings);

  for (const partConfig of recipe.parts) {
    const generator = getPartGenerator(partConfig.type);
    const result = generator.build(ctx, partConfig as ComponentRecipePart);
    ctx.addPartResult(partConfig.id, result);
  }

  const { graph } = assembleGraphFromContext({
    recipe,
    params: ctx.params,
    parameterSpecs: resolved.parameterSpecs,
    faces: ctx.faces,
    creases: ctx.creases,
    geometry: ctx.geometry,
    parts: ctx.parts,
    faceTreeHints: ctx.faceTreeHints,
    warnings: ctx.warnings,
  });

  assertValidDielineGraph(graph, recipe.label ?? recipe.id);
  return graph;
}

function createLayoutContext(recipe: DielineComponentRecipe, params: ParameterValueMap): ComponentLayoutContext {
  const ctx: ComponentLayoutContext = {
    recipe,
    params,
    faces: [],
    creases: [],
    geometry: [],
    anchors: new Map<string, Anchor>(),
    parts: [],
    faceTreeHints: [],
    warnings: [],
    getAnchor(anchorId: string): Anchor {
      const anchor = ctx.anchors.get(anchorId);
      if (!anchor) {
        throw new Error(`Missing anchor: ${anchorId}`);
      }
      return anchor;
    },
    numberValue(value: unknown, label: string): number {
      return resolveNumberExpression(value, ctx.params, label);
    },
    addPartResult(partId: string, result: PartResult) {
      for (const face of result.faces ?? []) {
        if (ctx.faces.some((candidate) => candidate.id === face.id)) {
          throw new Error(`Duplicate face id generated by part ${partId}: ${face.id}`);
        }
        ctx.faces.push(face);
      }

      for (const crease of result.structuralCreases ?? []) {
        if (ctx.creases.some((candidate) => candidate.id === crease.id)) {
          throw new Error(`Duplicate crease id generated by part ${partId}: ${crease.id}`);
        }
        ctx.creases.push(crease);
      }

      ctx.geometry.push(...(result.geometry ?? []));
      ctx.faceTreeHints.push(...(result.faceTreeHints ?? []));
      ctx.warnings.push(...(result.warnings ?? []));

      for (const anchor of result.anchors ?? []) {
        if (ctx.anchors.has(anchor.id)) {
          throw new Error(`Duplicate anchor id generated by part ${partId}: ${anchor.id}`);
        }
        ctx.anchors.set(anchor.id, anchor);
      }

      if (result.part) {
        ctx.parts.push(result.part);
      }
    },
  };

  return ctx;
}
