import type { V2PartContract } from "./types";

type ContractDraft = Pick<
  V2PartContract,
  "id" | "label" | "family" | "sourceDocPartId" | "implementationStatus"
> & Partial<Omit<V2PartContract, "id" | "label" | "family" | "sourceDocPartId" | "implementationStatus" | "productionReady">>;

function contract(definition: ContractDraft): V2PartContract {
  return {
    requiredAnchors: [],
    allowedAttachTargets: [],
    inputs: [],
    outputs: {},
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: false,
    createsAnchors: false,
    validationRules: ["All generated coordinates must be finite.", "No generated face may self-intersect."],
    warningRules: ["JSON documentation alone is not production verification."],
    foldingNotes: [],
    artworkNotes: [],
    productionRisks: ["Physical prototype and CAD/reference validation are required before production use."],
    usedByTemplates: [],
    ...definition,
    productionReady: false,
  };
}

const faceHingeRules = [
  "Base edge must match the attach anchor.",
  "Only the face-to-face hinge is a structural crease.",
];

const primitiveOnlyRules = [
  "This part creates GeometryPrimitive output only.",
  "It must never create a DielineCrease.",
];

const clearanceWarning = "Clearance and material-thickness behavior must be prototype verified.";

export const foldingBoxPartContracts = [
  contract({
    id: "standardBodyStrip",
    label: "Standard Body Strip",
    family: "body-systems",
    sourceDocPartId: "body-strip",
    implementationStatus: "implemented-experimental",
    inputs: [
      { name: "L", label: "Length", unit: "mm", required: true },
      { name: "W", label: "Width", unit: "mm", required: true },
      { name: "H", label: "Height", unit: "mm", required: true },
      { name: "T", label: "Material thickness", unit: "mm" },
      { name: "GFW", label: "Glue flap width", unit: "mm" },
      { name: "panelOrder", label: "Flat panel order", description: "Optional hidden assembly layout hint. Default remains V2-native." },
      { name: "xOffset", label: "Flat layout X offset", description: "Optional hidden assembly layout offset used when left-side attachments would otherwise render in negative SVG space." },
    ],
    outputs: {
      faces: ["front, back, side-A, and side-B body panels"],
      structuralCreases: ["vertical face-to-face body corner hinges"],
      anchors: ["top, bottom, left, and right anchors for every panel"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: ["L, W, and H must be positive.", "W should be <= L by the documentation convention.", "No panel width may be zero or negative."],
    warningRules: ["Warn when W > L.", "Warn that material thickness compensation is not yet production-calibrated."],
    foldingNotes: ["The body strip folds into the rectangular tube that receives all closure, glue, display, and internal parts."],
    artworkNotes: ["Body panels are printable; bleed and safe-area helpers are separate guide parts."],
    productionRisks: ["Board grain and inner/outer dimension policy must be confirmed."],
    usedByTemplates: ["reverseTuckEnd", "straightTuckEnd", "autoLockBottom", "snapLockBottom", "with-locking-tab-on-top-and-bottom", "carton-with-integrated-partitions", "carton-with-centered-divider", "carton-with-three-windows", "centered-tuck-end-carton", "tuck-end-folding-carton"],
  }),
  contract({
    id: "sleeveBody",
    label: "Sleeve Body",
    family: "body-systems",
    sourceDocPartId: "sleeve-body",
    implementationStatus: "implemented-experimental",
    inputs: [{ name: "L", required: true }, { name: "W", required: true }, { name: "H", required: true }, { name: "GFW" }],
    outputs: {
      faces: ["front and back sleeve panels"],
      structuralCreases: ["front/back sleeve hinge"],
      anchors: ["edge anchors for sleeve panels"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: ["L, W, and H must be positive.", "L should be greater than W for skillet-like sleeves."],
    warningRules: ["Warn when sleeve proportions are not landscape-oriented."],
    foldingNotes: ["Sleeve forms the shallow body shell for skillet and separated structures."],
    artworkNotes: ["Sleeve panels remain printable."],
    productionRisks: ["Skillet end closures require separate verification."],
    usedByTemplates: ["reversible-lid-skillet-carton", "separated-skillet-box"],
  }),
  contract({
    id: "sideGlueSeamTab",
    label: "Side Glue Seam Tab",
    family: "glue-systems",
    sourceDocPartId: "side-glue-tab",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:left", "anchor:right"],
    inputs: [{ name: "GFW", label: "Glue flap width", unit: "mm", required: true }, { name: "reliefBevel" }],
    outputs: {
      faces: ["glue seam face with end bevel relief"],
      structuralCreases: ["glue seam hinge"],
      geometryPrimitives: ["glue zone guide"],
      anchors: ["edge anchors for glue seam"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["GFW should normally be 10-20mm.", "Glue seam base edge must equal its attach anchor.", "Glue zone remains geometry-only."],
    warningRules: ["Warn outside typical glue seam width range."],
    foldingNotes: ["Factory glued last to close the carton tube.", "End bevels relieve interference with top and bottom closures."],
    artworkNotes: ["Mark as no-print adhesive area."],
    productionRisks: ["Adhesive dwell and glue width must be line-tested."],
    usedByTemplates: ["all"],
  }),
  contract({
    id: "relievedGlueSeamTab",
    label: "Relieved Glue Seam Tab",
    family: "glue-systems",
    sourceDocPartId: "side-glue-tab",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:left", "anchor:right"],
    inputs: [{ name: "GFW", required: true }, { name: "reliefDepth" }, { name: "reliefInset" }],
    outputs: {
      faces: ["glue seam face with relieved corners"],
      structuralCreases: ["glue seam hinge"],
      geometryPrimitives: ["glue zone and relief cut guides"],
      anchors: ["edge anchors for relieved seam"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Reliefs must leave positive glue area.", "Relief cuts remain GeometryPrimitive objects."],
    warningRules: ["Warn when relief is large relative to glue width."],
    foldingNotes: ["Relieved corners reduce closure interference at the seam."],
    artworkNotes: ["Relieved glue zones stay no-print."],
    productionRisks: ["Oversized reliefs reduce bond area."],
    usedByTemplates: ["advanced seam variants"],
  }),
  contract({
    id: "standardTuckClosureFlap",
    label: "Standard Tuck Closure Flap",
    family: "top-closures",
    sourceDocPartId: "reverse-tuck-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TFR" }, { name: "DFW" }, { name: "lipScoreOffset" }],
    outputs: {
      faces: ["shared tuck closure flap face"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["optional geometry-only lip score"],
      anchors: ["edge anchors for tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "TFW should be >= 12mm and should not exceed the internal box width.", "Lip score details remain GeometryPrimitive objects.", "Straight tuck and reverse tuck assemblies may use this same geometry because their difference is template-level attachment."],
    warningRules: ["Warn when TFW is unusually short or long.", "Lip-score geometry remains sample/reference-sensitive."],
    foldingNotes: ["Dust flaps fold first; the tuck flap folds inward and tucks behind them.", "Reverse-vs-straight tuck behavior is controlled by which body panel owns the top and bottom closures."],
    artworkNotes: ["Exterior flap artwork can be visible during opening."],
    productionRisks: ["Short flaps fail to lock; long flaps buckle."],
    usedByTemplates: ["reverseTuckEnd", "straightTuckEnd"],
  }),
  contract({
    id: "reverseTuckClosureFlap",
    label: "Reverse Tuck Closure Flap",
    family: "top-closures",
    sourceDocPartId: "reverse-tuck-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TFR" }, { name: "DFW" }, { name: "lipScoreOffset" }],
    outputs: {
      faces: ["tuck closure flap face"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["optional lock notch cut guides", "optional geometry-only lip score"],
      anchors: ["edge anchors for tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "TFW should be >= 12mm and should not exceed the internal box width.", "Lip score and notch details remain GeometryPrimitive objects."],
    warningRules: ["Warn when TFW is unusually short or long.", "Lock notch and lip-score geometry remain sample/reference-sensitive."],
    foldingNotes: ["Dust flaps fold first; the tuck flap folds inward and tucks behind them."],
    artworkNotes: ["Exterior flap artwork can be visible during opening."],
    productionRisks: ["Short flaps fail to lock; long flaps buckle."],
    usedByTemplates: ["reverseTuckEnd", "autoLockBottom", "snapLockBottom", "with-circular-hang-hole"],
  }),
  contract({
    id: "straightTuckClosureFlap",
    label: "Straight Tuck Closure Flap",
    family: "top-closures",
    sourceDocPartId: "straight-tuck-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TFR" }, { name: "DFW" }],
    outputs: {
      faces: ["straight tuck closure flap face"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["optional notch cut guides"],
      anchors: ["edge anchors for straight tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Straight tuck orientation is template-level and must be checked visually."],
    foldingNotes: ["Both ends tuck from the same direction in straight tuck cartons."],
    artworkNotes: ["Often chosen for consistent loading direction."],
    productionRisks: ["Can create asymmetric finished appearance."],
    usedByTemplates: ["straightTuckEnd"],
  }),
  contract({
    id: "centeredTuckClosureFlap",
    label: "Centered Tuck Closure Flap",
    family: "top-closures",
    sourceDocPartId: "centered-tuck-flap",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW1", required: true }, { name: "TFW2" }, { name: "D1", required: true }, { name: "D2" }, { name: "TFR" }],
    outputs: {
      faces: ["centered / angled tuck flap face"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["leading-edge guide"],
      anchors: ["edge anchors for centered tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "D1 must be positive.", "TFW1 should reach past the centerline of the opening."],
    warningRules: ["Partial-experimental: angled leading edge needs overlay/reference verification."],
    foldingNotes: ["The angled center profile is intended to clear companion dust and lock features."],
    artworkNotes: ["Angled edge can interrupt artwork near the leading flap boundary."],
    productionRisks: ["Complex leading edge requires die verification."],
    usedByTemplates: ["centered-tuck-end-carton"],
  }),
  contract({
    id: "fullWidthTuckClosureFlap",
    label: "Full Width Tuck Closure Flap",
    family: "top-closures",
    sourceDocPartId: "reverse-tuck-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TFR" }, { name: "lipScoreOffset" }],
    outputs: {
      faces: ["full-width tuck closure face"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["lip score guide"],
      anchors: ["edge anchors for full-width tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Lip score remains geometry-only."],
    warningRules: ["Warn on wide anchors because stiffness must be checked."],
    foldingNotes: ["Acts as a full-width insert flap that can receive display or lock subparts."],
    artworkNotes: ["Can carry branding or instructions."],
    productionRisks: ["Large flaps require die and stiffness checks."],
    usedByTemplates: ["with-circular-hang-hole", "with-hang-tab", "tuck-end-folding-carton"],
  }),
  contract({
    id: "lockingLipClosureFlap",
    label: "Locking Lip Closure Flap",
    family: "top-closures",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TL", required: true }, { name: "TD1", required: true }, { name: "TR" }, { name: "PR" }],
    outputs: {
      faces: ["locking flap with integrated tab"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["tab shoulder score"],
      anchors: ["edge anchors for lock flap and tab"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "TL must leave side margins.", "Receiving slot is a separate geometry-only part."],
    warningRules: [clearanceWarning],
    foldingNotes: ["Tab bends into a receiving slot after dust flaps fold inward."],
    artworkNotes: ["Slot position should avoid primary branding areas."],
    productionRisks: ["Tight slots tear paper; loose slots do not lock."],
    usedByTemplates: ["with-locking-tab-on-top-and-bottom", "carton-with-three-windows"],
  }),
  contract({
    id: "standardDustFlap",
    label: "Standard Dust Flap",
    family: "dust-flaps",
    sourceDocPartId: "dust-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "DFW", required: true }, { name: "taper" }, { name: "shoulder" }, { name: "reliefDepth" }, { name: "sidePosition" }],
    outputs: {
      faces: ["shouldered tapered dust flap face"],
      structuralCreases: ["side-panel-to-dust-flap hinge"],
      anchors: ["edge anchors for dust flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "DFW should be less than half the box opening.", "Dust flap taper must leave a positive leading edge.", "Left and right dust flaps must be handed, not identical translated polygons.", "Shoulder/relief detail is part of the cut outline and must not become a DielineCrease."],
    warningRules: ["Warn when DFW approaches or exceeds half-width.", "Warn when taper removes too much dust-sealing area."],
    foldingNotes: ["Dust flaps fold inward before main closure panels."],
    artworkNotes: ["Usually interior and unprinted."],
    productionRisks: ["Exact half-width dust flaps can jam."],
    usedByTemplates: ["reverseTuckEnd", "straightTuckEnd", "with-circular-hang-hole", "with-hang-tab"],
  }),
  contract({
    id: "trapezoidDustFlap",
    label: "Trapezoid Dust Flap",
    family: "dust-flaps",
    sourceDocPartId: "dust-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "DFW", required: true }, { name: "taper" }],
    outputs: {
      faces: ["trapezoidal dust flap face"],
      structuralCreases: ["dust flap hinge"],
      anchors: ["edge anchors for trapezoid dust flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Taper must not collapse the free edge."],
    warningRules: ["Warn when taper is large relative to anchor width."],
    foldingNotes: ["Taper reduces side interference during closure insertion."],
    artworkNotes: ["Usually an interior support surface."],
    productionRisks: ["Too much taper reduces dust sealing."],
    usedByTemplates: ["decorative tuck-end variants", "locking tab variants"],
  }),
  contract({
    id: "angledBottomDustFlap",
    label: "Angled Bottom Dust Flap",
    family: "dust-flaps",
    sourceDocPartId: "dust-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "DFW", required: true }, { name: "startInset" }, { name: "endInset" }],
    outputs: {
      faces: ["angled bottom dust flap face"],
      structuralCreases: ["bottom side-panel hinge"],
      anchors: ["edge anchors for angled bottom dust flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Insets must leave a positive free edge."],
    warningRules: ["Warn when bottom dust flap may interfere with lock bottom pieces."],
    foldingNotes: ["Bottom dust flaps fold before bottom lock or snap-lock flaps."],
    artworkNotes: ["Usually an interior bottom surface."],
    productionRisks: ["Bottom closure interference must be checked physically."],
    usedByTemplates: ["snap-lock-bottom variants", "tuck-end-folding-carton"],
  }),
  contract({
    id: "bottomLockFlap",
    label: "Bottom Lock Flap",
    family: "bottom-closures",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "bodyDepth", required: true }, { name: "tongueDepth" }, { name: "tongueWidth" }],
    outputs: {
      faces: ["bottom lock flap with tongue"],
      structuralCreases: ["bottom body-to-lock-flap hinge"],
      geometryPrimitives: ["tongue shoulder score"],
      anchors: ["edge anchors for lock flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Tongue width must be less than flap width.", "Tongue score is geometry-only."],
    warningRules: ["Warn because full snap-lock assembly remains reference-pending."],
    foldingNotes: ["One prerequisite Lego piece of the snap-lock bottom."],
    artworkNotes: ["Bottom exterior can carry production marks."],
    productionRisks: ["Tongue and slot clearances are material-thickness sensitive."],
    usedByTemplates: ["snap-lock-bottom variants"],
  }),

  contract({
    id: "snapLockBottomPanel",
    label: "Snap-Lock Bottom Panel Assembly",
    family: "bottom-closures",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "spec-only",
    requiredAnchors: ["front.bottom", "back.bottom", "sideA.bottom", "sideB.bottom"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "DFW" }, { name: "GFW" }, { name: "tongueWidth" }, { name: "slotWidth" }],
    outputs: {
      faces: ["major tongue flap", "major receiver flap", "minor side flaps"],
      structuralCreases: ["four bottom face-to-face hinges"],
      geometryPrimitives: ["receiver slot cutout"],
      anchors: ["bottom assembly anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Tongue width must be less than slot width by clearance.", "Slot remains GeometryPrimitive only.", "Minor flap height must be < W/2."],
    warningRules: ["Spec-only until full interlock is reference/prototype validated."],
    foldingNotes: ["Minor flaps fold first, receiver folds next, tongue flap locks last."],
    artworkNotes: ["Receiver slot may affect barcode placement."],
    productionRisks: ["Interlock clearance controls assembly force and load capacity."],
    usedByTemplates: ["snapLockBottom", "centered-tuck-end-carton", "tuck-end-folding-carton"],
  }),
  contract({
    id: "snapLockMajorFlap",
    label: "Snap-Lock Major Flap",
    family: "bottom-closures",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "flapDepth" }, { name: "DFW" }],
    outputs: {
      faces: ["major bottom flap face"],
      structuralCreases: ["bottom flap hinge"],
      anchors: ["edge anchors for major flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: [clearanceWarning, "Part is a graph-valid subpiece, not the full snap-lock system."],
    foldingNotes: ["Pairs with a tongue, receiver slot, and minor flaps."],
    artworkNotes: ["Bottom outside may carry small marks."],
    productionRisks: ["Exact major-flap depth is load and clearance sensitive."],
    usedByTemplates: ["snap-lock-bottom variants"],
  }),
  contract({
    id: "snapLockMinorFlap",
    label: "Snap-Lock Minor Flap",
    family: "bottom-closures",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "DFW" }, { name: "clearanceTaper" }],
    outputs: {
      faces: ["minor bottom flap face"],
      structuralCreases: ["bottom minor flap hinge"],
      anchors: ["edge anchors for minor flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Minor flap height should be < W/2."],
    warningRules: [clearanceWarning],
    foldingNotes: ["Minor flaps tuck inward before the major lock flaps."],
    artworkNotes: ["Usually hidden inside bottom stack."],
    productionRisks: ["Oversized minor flaps jam under snap-lock flaps."],
    usedByTemplates: ["snap-lock-bottom variants"],
  }),
  contract({
    id: "snapLockTongue",
    label: "Snap-Lock Tongue",
    family: "bottom-closures",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "tongueWidth" }, { name: "tongueDepth" }, { name: "bodyDepth" }],
    outputs: {
      faces: ["snap tongue face"],
      structuralCreases: ["tongue parent hinge"],
      geometryPrimitives: ["tongue shoulder score"],
      anchors: ["edge anchors for tongue piece"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Tongue depth should remain <= about 8mm unless verified."],
    warningRules: [clearanceWarning],
    foldingNotes: ["Tongue inserts into snapLockReceiverSlot."],
    artworkNotes: ["Usually internal."],
    productionRisks: ["Too wide or deep makes assembly difficult."],
    usedByTemplates: ["snap-lock-bottom variants"],
  }),
  contract({
    id: "snapLockReceiverSlot",
    label: "Snap-Lock Receiver Slot",
    family: "bottom-closures",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "slotWidth" }, { name: "slotHeight" }, { name: "radius" }],
    outputs: { geometryPrimitives: ["rounded receiver slot"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Receives the snap-lock tongue."],
    artworkNotes: ["Avoid placing barcode-critical art over slot."],
    productionRisks: ["Slot too large can unlock accidentally."],
    usedByTemplates: ["snap-lock-bottom variants"],
  }),
  contract({
    id: "autoLockBottomPanel",
    label: "Auto-Lock Bottom Panel Assembly",
    family: "bottom-closures",
    sourceDocPartId: "auto-lock-bottom-panel",
    implementationStatus: "spec-only",
    requiredAnchors: ["front.bottom", "back.bottom", "sideA.bottom", "sideB.bottom"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "GFW" }, { name: "DFW" }, { name: "overlap" }],
    outputs: {
      faces: ["major flaps", "minor flaps", "auto-lock glue panel"],
      structuralCreases: ["bottom hinges"],
      geometryPrimitives: ["diagonal score guides", "pre-glue zone"],
      anchors: ["bottom assembly anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Diagonal scores are geometry guides unless they split independently foldable subfaces.", "Pre-glue zone is geometry-only."],
    warningRules: ["Spec-only because diagonal score geometry requires reference/prototype validation."],
    foldingNotes: ["Factory pre-glued bottom springs open when the carton tube is erected."],
    artworkNotes: ["Major bottom surfaces can carry barcode and production marks."],
    productionRisks: ["Diagonal score angle is critical to flat collapse and pop-open behavior."],
    usedByTemplates: ["autoLockBottom", "with-handle", "auto-lock-bottom-carton-with-tab-closure", "gusset-cover-crash-bottom-carton"],
  }),
  contract({
    id: "autoLockMajorFlap",
    label: "Auto-Lock Major Flap",
    family: "bottom-closures",
    sourceDocPartId: "auto-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "majorDepth" }, { name: "overlap" }],
    outputs: {
      faces: ["major auto-lock flap face"],
      structuralCreases: ["bottom hinge"],
      anchors: ["edge anchors for major flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Major flap height should be at least W/2 plus overlap."],
    warningRules: ["Partial-experimental: diagonal relation to companion flaps is not verified."],
    foldingNotes: ["Receives autoLockDiagonalScore and factory glue relationships."],
    artworkNotes: ["Barcode placement must avoid glue/score areas."],
    productionRisks: ["Wrong depth prevents flat collapse or reliable pop-open."],
    usedByTemplates: ["auto-lock-bottom variants"],
  }),
  contract({
    id: "autoLockMinorFlap",
    label: "Auto-Lock Minor Flap",
    family: "bottom-closures",
    sourceDocPartId: "auto-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "DFW" }, { name: "clearanceTaper" }],
    outputs: {
      faces: ["minor auto-lock flap face"],
      structuralCreases: ["minor flap hinge"],
      anchors: ["edge anchors for minor flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Minor flap depth should be < W/2."],
    warningRules: ["Partial-experimental: nesting with major flaps must be checked."],
    foldingNotes: ["Minor flaps fold into the auto-lock stack."],
    artworkNotes: ["Usually hidden inside bottom closure."],
    productionRisks: ["Oversized minor flaps interfere with crash-lock motion."],
    usedByTemplates: ["auto-lock-bottom variants"],
  }),
  contract({
    id: "autoLockGluePanel",
    label: "Auto-Lock Glue Panel",
    family: "bottom-closures",
    sourceDocPartId: "auto-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "GFW" }],
    outputs: {
      faces: ["pre-glue panel face"],
      structuralCreases: ["glue panel hinge"],
      anchors: ["edge anchors for auto-lock glue panel"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Glue panel should allow at least 10mm adhesive coverage."],
    warningRules: ["Partial-experimental: factory pre-glue relationship is not fully modeled."],
    foldingNotes: ["Pre-glued to an opposite major flap to form the spring-lock action."],
    artworkNotes: ["No-print adhesive zone should be added with bottomGlueZone."],
    productionRisks: ["Wrong glue panel placement prevents collapse/open action."],
    usedByTemplates: ["auto-lock-bottom variants"],
  }),
  contract({
    id: "autoLockDiagonalScore",
    label: "Auto-Lock Diagonal Score",
    family: "bottom-closures",
    sourceDocPartId: "auto-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }],
    outputs: { geometryPrimitives: ["diagonal score guide"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Partial-experimental: diagonal score angle is the critical unverified variable."],
    foldingNotes: ["Represented as a score guide unless future assembly splits true subfaces."],
    artworkNotes: ["Score should be visible on manufacturing layer, not cut."],
    productionRisks: ["Wrong angle makes the crash-lock bottom fail."],
    usedByTemplates: ["auto-lock-bottom variants"],
  }),
  contract({
    id: "crashBottomPanel",
    label: "Crash Bottom Panel Assembly",
    family: "bottom-closures",
    sourceDocPartId: "auto-lock-bottom-panel",
    implementationStatus: "spec-only",
    requiredAnchors: ["front.bottom", "back.bottom", "sideA.bottom", "sideB.bottom"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "GFW" }, { name: "DFW" }, { name: "overlap" }],
    outputs: {
      faces: ["pre-glued crash-lock bottom flaps"],
      structuralCreases: ["bottom hinges"],
      geometryPrimitives: ["diagonal score guides", "glue zones"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    validationRules: ["Must match auto-lock diagonal score behavior."],
    warningRules: ["Spec-only until exact crash-lock construction is verified."],
    foldingNotes: ["Equivalent high-risk family to auto-lock/crash-lock bottom."],
    artworkNotes: ["Bottom print must avoid glue and score regions."],
    productionRisks: ["Requires factory pre-glue and folding-line validation."],
    usedByTemplates: ["crash-bottom-carton-with-tear-strip", "gusset-cover-crash-bottom-carton"],
  }),
  contract({
    id: "fullFlapBottomPanel",
    label: "Full-Flap Bottom Panel",
    family: "bottom-closures",
    sourceDocPartId: "full-flap-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "fullFlapDepth" }, { name: "TFW" }, { name: "GFW" }, { name: "DFW" }],
    outputs: {
      faces: ["full-width bottom flap face"],
      structuralCreases: ["bottom hinge"],
      anchors: ["edge anchors for full flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Full flap height should cover the full base width plus overlap."],
    warningRules: ["Partial-experimental: diagonal score behavior for full-flap bottom is not modeled."],
    foldingNotes: ["Oversized flap covers the full base and may interact with auto-lock glue geometry."],
    artworkNotes: ["Large printable bottom surface."],
    productionRisks: ["Non-standard diagonal score geometry requires die verification."],
    usedByTemplates: ["autoLockBottomWithFullFlap"],
  }),
  contract({
    id: "bottomGlueZone",
    label: "Bottom Glue Zone",
    family: "bottom-closures",
    sourceDocPartId: "auto-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "glueHeight" }],
    outputs: { geometryPrimitives: ["bottom adhesive zone"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Glue zone size and placement are production-line dependent."],
    foldingNotes: ["Guides adhesive placement only."],
    artworkNotes: ["No critical print inside glue zone."],
    productionRisks: ["Glue area too small can fail under load."],
    usedByTemplates: ["auto-lock-bottom variants", "full-flap-bottom variants"],
  }),

  contract({
    id: "circularCutout",
    label: "Circular Cutout",
    family: "cutouts",
    sourceDocPartId: "circular-hang-hole",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "OD" }, { name: "radius" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["circle cutout"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Warn when hole diameter is outside typical peg-hook range."],
    foldingNotes: ["Cutout remains a hole after folding."],
    artworkNotes: ["Keep critical artwork away from punched hole."],
    productionRisks: ["Off-center holes make products tilt on pegs."],
    usedByTemplates: ["with-circular-hang-hole"],
  }),
  contract({
    id: "roundedSlotCutout",
    label: "Rounded Slot Cutout",
    family: "cutouts",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "width", required: true }, { name: "height", required: true }, { name: "radius" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["rounded slot cutout"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Receives a locking tab or snap tongue."],
    artworkNotes: ["Avoid primary artwork over lock slots."],
    productionRisks: ["Slot clearance controls assembly force."],
    usedByTemplates: ["with-locking-tab-on-top-and-bottom", "snap-lock-bottom variants"],
  }),
  contract({
    id: "euroSlotCutout",
    label: "Euro Slot Cutout",
    family: "cutouts",
    sourceDocPartId: "hang-tab",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "SL", required: true }, { name: "SW", required: true }, { name: "FR" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["euro slot cutout"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Warn when slot is large relative to tab width."],
    foldingNotes: ["Slot is punched through display tab reinforcement."],
    artworkNotes: ["Peg-display artwork should account for the slot."],
    productionRisks: ["Slot position relative to fold crease is critical."],
    usedByTemplates: ["with-hang-tab"],
  }),
  contract({
    id: "windowCutout",
    label: "Window Cutout",
    family: "windows",
    sourceDocPartId: "window-cutout",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "WL", required: true }, { name: "WH", required: true }, { name: "WR" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["rounded rectangle window cutout"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Warn when window removes too much panel area."],
    foldingNotes: ["Window is cut before folding and keeps shape in 3D."],
    artworkNotes: ["Mark clear film zone and maintain margin around window."],
    productionRisks: ["Windows weaken panels near creases; film adhesion must be specified."],
    usedByTemplates: ["carton-with-three-windows", "with-circular-hang-hole-and-window", "with-handle-and-window"],
  }),
  contract({
    id: "reliefNotch",
    label: "Relief Notch",
    family: "cutouts",
    sourceDocPartId: "unknownsAndNeedsManualReview.corner-relief-notches",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "width", required: true }, { name: "depth", required: true }, { name: "position" }],
    outputs: { geometryPrimitives: ["relief notch cut path"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Exact relief style is not exposed as a CefBox parameter."],
    foldingNotes: ["Relief reduces cracking and interference where folds meet."],
    artworkNotes: ["Avoid artwork-critical details at relief cuts."],
    productionRisks: ["Relief radius and shape require die verification."],
    usedByTemplates: ["all folding cartons as optional relief"],
  }),

  contract({
    id: "hangPanel",
    label: "Hang Panel",
    family: "hang-display",
    sourceDocPartId: "circular-hang-hole",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "HL", required: true }, { name: "HW" }],
    outputs: {
      faces: ["rectangular hang panel extension"],
      structuralCreases: ["tuck/hang panel hinge"],
      anchors: ["edge anchors for hang panel"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Single-layer hang panel strength must be verified."],
    foldingNotes: ["Panel folds with or above the tuck assembly."],
    artworkNotes: ["Visible peg-display surface."],
    productionRisks: ["Single-layer hang panels can tear under product weight."],
    usedByTemplates: ["with-circular-hang-hole"],
  }),
  contract({
    id: "sideCircularHangPanel",
    label: "Side Circular Hang Panel",
    family: "hang-display",
    sourceDocPartId: "circular-hang-hole",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:right"],
    inputs: [{ name: "extensionWidth", required: true }, { name: "neckWidth" }, { name: "outerRadius" }, { name: "centerY" }],
    outputs: {
      faces: ["right-side rounded/circular hang extension"],
      structuralCreases: ["body-to-side-hanger hinge"],
      anchors: ["edge anchors for side circular hang panel"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Side hanger must attach to the right edge for the circular-hang-hole reference structure.", "Circular hole remains a separate GeometryPrimitive cutout."],
    warningRules: ["Side hang strength, tear resistance, and board grain must be prototype verified."],
    foldingNotes: ["The side circular hanger folds from the rightmost side panel rather than from a top closure."],
    artworkNotes: ["Keep branding clear of the punched circular hole and hanger neck."],
    productionRisks: ["Rounded side hangers can tear if the neck is too narrow or material is weak."],
    usedByTemplates: ["with-circular-hang-hole"],
  }),
  contract({
    id: "hangTab",
    label: "Folded Hang Tab",
    family: "hang-display",
    sourceDocPartId: "hang-tab",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "TW", required: true }, { name: "SAL", required: true }, { name: "SL" }, { name: "SW" }, { name: "FR" }],
    outputs: {
      faces: ["inner and outer tab halves"],
      structuralCreases: ["tab attachment hinge", "tab midpoint fold hinge"],
      geometryPrimitives: ["euro slot cutout"],
      anchors: ["edge anchors for tab halves"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["TW must be wide enough for slot margins.", "Midpoint fold is a structural face-to-face hinge."],
    warningRules: ["Display-load behavior needs prototype validation."],
    foldingNotes: ["Outer half folds 180 degrees onto inner half and is glued for double thickness."],
    artworkNotes: ["Both faces can be visible in peg display workflows."],
    productionRisks: ["Tab centering and slot position determine hanging stability."],
    usedByTemplates: ["with-hang-tab"],
  }),

  contract({
    id: "lockTab",
    label: "Lock Tab",
    family: "lock-tabs",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TL" }, { name: "TD1" }, { name: "TR" }],
    outputs: {
      faces: ["protruding lock tab face"],
      structuralCreases: ["tab attachment hinge"],
      geometryPrimitives: ["tab shoulder score"],
      anchors: ["edge anchors for lock tab"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: [...faceHingeRules, "Tab width must leave margins."],
    warningRules: [clearanceWarning],
    foldingNotes: ["Tab inserts into lockSlot or roundedSlotCutout."],
    artworkNotes: ["Usually hidden or partially visible."],
    productionRisks: ["Fit is sensitive to slot clearance and board caliper."],
    usedByTemplates: ["with-locking-tab-on-top-and-bottom", "snap-lock-bottom-carton-with-tab-closure"],
  }),
  contract({
    id: "lockSlot",
    label: "Lock Slot",
    family: "lock-tabs",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "TL" }, { name: "TD1" }, { name: "PR" }],
    outputs: { geometryPrimitives: ["lock receiver slot"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Receives a lock tab; does not become a crease."],
    artworkNotes: ["Avoid important print over the slot."],
    productionRisks: ["Slot too tight tears; too loose opens accidentally."],
    usedByTemplates: ["with-locking-tab-on-top-and-bottom", "tab-closure variants"],
  }),
  contract({
    id: "lockingTuckFlap",
    label: "Locking Tuck Flap",
    family: "lock-tabs",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW" }, { name: "TL" }, { name: "TD1" }],
    outputs: {
      faces: ["tuck flap with protruding tab"],
      structuralCreases: ["closure hinge"],
      geometryPrimitives: ["tab shoulder score"],
      anchors: ["anchors for locking tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Combines a tuck flap body and lock-tab tongue."],
    artworkNotes: ["Slot receiver should be planned in the mating face."],
    productionRisks: ["Tab and receiver geometry must be tested together."],
    usedByTemplates: ["with-locking-tab-on-top-and-bottom"],
  }),
  contract({
    id: "catalogLockFlap",
    label: "Catalog Lock Flap",
    family: "lock-tabs",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW" }, { name: "TFR" }],
    outputs: {
      faces: ["catalog-style locking flap"],
      structuralCreases: ["closure hinge"],
      anchors: ["edge anchors for catalog lock"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Used as a simple locking closure body before sub-tabs/slots are attached."],
    artworkNotes: ["Can carry visible closure artwork."],
    productionRisks: ["Catalog-lock shapes are tolerance-sensitive."],
    usedByTemplates: ["carton-with-three-windows", "tab-closure variants"],
  }),
  contract({
    id: "snapLockingLip",
    label: "Snap Locking Lip",
    family: "lock-tabs",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "lipDepth" }, { name: "snapDepth" }, { name: "snapWidth" }],
    outputs: {
      faces: ["snap locking lip face"],
      structuralCreases: ["lip hinge"],
      geometryPrimitives: ["lip shoulder score"],
      anchors: ["edge anchors for snap lip"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["A smaller lip/tongue piece for snap-lock interactions."],
    artworkNotes: ["Usually hidden inside the bottom stack."],
    productionRisks: ["Snap force depends on caliper and slot size."],
    usedByTemplates: ["snap-lock-bottom variants"],
  }),
  contract({
    id: "lockReliefNotch",
    label: "Lock Relief Notch",
    family: "lock-tabs",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "notchWidth" }, { name: "notchDepth" }],
    outputs: { geometryPrimitives: ["lock relief notch"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Relief size must be verified with tab/slot tooling."],
    foldingNotes: ["Relieves stress around locking features."],
    artworkNotes: ["Keep print detail away from relief."],
    productionRisks: ["Oversized relief weakens the closure."],
    usedByTemplates: ["tab-closure variants"],
  }),

  contract({
    id: "foldedHandle",
    label: "Folded Handle",
    family: "handles",
    sourceDocPartId: "folded-handle",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "HL" }, { name: "HW" }, { name: "HT" }, { name: "FW1" }, { name: "FW2" }],
    outputs: {
      faces: ["folded handle panel"],
      structuralCreases: ["handle attachment hinge"],
      anchors: ["edge anchors for handle subparts"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Partial-experimental: multi-panel carry-load behavior is not fully modeled."],
    foldingNotes: ["Folded handle requires a multi-stage fold sequence and reinforcement stack-up."],
    artworkNotes: ["Handle panels often expose both sides."],
    productionRisks: ["Carry load, board grain, and hand comfort require prototype testing."],
    usedByTemplates: ["with-handle", "with-handle-and-window"],
  }),
  contract({
    id: "arcHandle",
    label: "Arc Handle",
    family: "handles",
    sourceDocPartId: "arc-handle",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "HT" }, { name: "HR" }, { name: "SR" }],
    outputs: {
      faces: ["arc handle grip panel"],
      structuralCreases: ["arc handle hinge"],
      anchors: ["edge anchors for grip panel"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Partial-experimental: arch cutout and grip interlock need reference validation."],
    foldingNotes: ["Arc grip folds outward from a matching body-panel cutout."],
    artworkNotes: ["Cutout comfort radii should avoid sharp paper edges."],
    productionRisks: ["Handle can collapse under load without correct reinforcement."],
    usedByTemplates: ["snap-lock-carton-with-arc-handler"],
  }),
  contract({
    id: "handleBridge",
    label: "Handle Bridge",
    family: "handles",
    sourceDocPartId: "folded-handle",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "bridgeDepth" }],
    outputs: {
      faces: ["handle bridge reinforcement face"],
      structuralCreases: ["bridge hinge"],
      anchors: ["bridge anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Partial-experimental: load path is not verified."],
    foldingNotes: ["Bridge reinforces the grip opening."],
    artworkNotes: ["Usually hidden or interior-facing."],
    productionRisks: ["Undersized bridge tears under product load."],
    usedByTemplates: ["with-handle"],
  }),
  contract({
    id: "handleCutout",
    label: "Handle Cutout",
    family: "handles",
    sourceDocPartId: "arc-handle",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "HW" }, { name: "HT" }, { name: "HR" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["handle opening cutout"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Grip comfort and panel strength require prototype validation."],
    foldingNotes: ["Cutout removes material and never becomes a crease."],
    artworkNotes: ["Keep artwork clear of hand opening."],
    productionRisks: ["Cutout too wide weakens panel."],
    usedByTemplates: ["with-handle", "snap-lock-carton-with-arc-handler", "with-handle-and-window"],
  }),
  contract({
    id: "handleReinforcementPanel",
    label: "Handle Reinforcement Panel",
    family: "handles",
    sourceDocPartId: "folded-handle",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "reinforcementDepth" }],
    outputs: {
      faces: ["reinforcement face"],
      structuralCreases: ["reinforcement hinge"],
      anchors: ["reinforcement anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Partial-experimental: reinforcement stack-up is not verified."],
    foldingNotes: ["Adds extra board thickness around the handle."],
    artworkNotes: ["May be glue/no-print depending on stack-up."],
    productionRisks: ["Misaligned reinforcement creates weak carry points."],
    usedByTemplates: ["with-handle"],
  }),

  contract({
    id: "tearStrip",
    label: "Tear Strip",
    family: "tear-perforation",
    sourceDocPartId: "tear-strip",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "EXD" }, { name: "stripWidth" }, { name: "R1" }, { name: "R2" }, { name: "GFA" }],
    outputs: { geometryPrimitives: ["upper and lower perforation lines"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Perforation pitch and tear behavior must be die-verified."],
    foldingNotes: ["Tear strip is represented as guide/perforation geometry unless future split faces are required."],
    artworkNotes: ["Artwork should anticipate consumer tear path."],
    productionRisks: ["Too much perforation tears in transit; too little is hard to open."],
    usedByTemplates: ["gusset-roof-carton-with-tear-strip", "crash-bottom-carton-with-tear-strip", "snap-lock-bottom-with-tear-strip"],
  }),
  contract({
    id: "perforationStrip",
    label: "Perforation Strip",
    family: "tear-perforation",
    sourceDocPartId: "tear-strip",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }],
    outputs: { geometryPrimitives: ["perforation line"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Perforation layer is tooling-specific."],
    foldingNotes: ["Perforation guides tear path only."],
    artworkNotes: ["Avoid small text across perforation."],
    productionRisks: ["Tooling nick pattern controls opening force."],
    usedByTemplates: ["tear-strip variants"],
  }),
  contract({
    id: "tearPullTab",
    label: "Tear Pull Tab",
    family: "tear-perforation",
    sourceDocPartId: "tear-strip",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "pullWidth" }, { name: "pullDepth" }, { name: "tabBodyDepth" }],
    outputs: {
      faces: ["pull tab face"],
      structuralCreases: ["pull tab hinge"],
      geometryPrimitives: ["tab shoulder score"],
      anchors: ["pull tab anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Pull tab shape and seam break need prototype validation."],
    foldingNotes: ["Consumer grabs the tab to start tearing along perforations."],
    artworkNotes: ["Pull tab can carry open indication artwork."],
    productionRisks: ["Wrong tab geometry prevents clean tear start."],
    usedByTemplates: ["tear-strip variants"],
  }),
  contract({
    id: "tearNotch",
    label: "Tear Notch",
    family: "tear-perforation",
    sourceDocPartId: "tear-strip",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "notchWidth" }, { name: "notchDepth" }, { name: "R3" }],
    outputs: { geometryPrimitives: ["tear notch cutout"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Notch style and radius are tooling-specific."],
    foldingNotes: ["Notch provides a tear-start point."],
    artworkNotes: ["Avoid critical artwork at tear-start notch."],
    productionRisks: ["Oversized notch can start accidental tears."],
    usedByTemplates: ["tear-strip variants"],
  }),
  contract({
    id: "sealFlap",
    label: "Seal Flap",
    family: "tear-perforation",
    sourceDocPartId: "tear-strip",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "sealDepth" }],
    outputs: {
      faces: ["seal flap face"],
      structuralCreases: ["seal flap hinge"],
      anchors: ["seal flap anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Seal behavior with tear strip is not verified."],
    foldingNotes: ["Seal flap can overlap a tear strip area."],
    artworkNotes: ["May carry tamper/opening graphics."],
    productionRisks: ["Seal adhesive can block tear separation if placed incorrectly."],
    usedByTemplates: ["tear-strip variants"],
  }),

  contract({
    id: "centeredDivider",
    label: "Centered Divider",
    family: "internal-structures",
    sourceDocPartId: "centered-divider",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "DL" }, { name: "OD1" }, { name: "OD2" }],
    outputs: {
      faces: ["divider panel face"],
      structuralCreases: ["divider hinge"],
      anchors: ["divider anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["3D collision and material thickness must be checked."],
    foldingNotes: ["Divider folds inward to split the box into compartments."],
    artworkNotes: ["Usually interior-facing."],
    productionRisks: ["Divider width must account for material thickness."],
    usedByTemplates: ["carton-with-centered-divider", "carton-with-three-windows", "snap-lock-bottom-carton-with-divider"],
  }),
  contract({
    id: "integratedPartition",
    label: "Integrated Partition",
    family: "internal-structures",
    sourceDocPartId: "integrated-partition",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "PD1" }, { name: "PD2" }],
    outputs: {
      faces: ["partition panel face"],
      structuralCreases: ["partition hinge"],
      anchors: ["partition anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Cross-slot partition fit is reference-pending."],
    foldingNotes: ["Pairs with other partition panels and partitionLockSlot."],
    artworkNotes: ["Interior panel; print is optional."],
    productionRisks: ["Cross-slot tolerance controls assembly success."],
    usedByTemplates: ["carton-with-integrated-partitions"],
  }),
  contract({
    id: "builtInInsert",
    label: "Built-In Insert",
    family: "internal-structures",
    sourceDocPartId: "built-in-insert",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "D1" }, { name: "D2" }, { name: "D3" }, { name: "D4" }, { name: "D5" }, { name: "D6" }],
    outputs: {
      faces: ["insert panel face"],
      structuralCreases: ["insert hinge"],
      anchors: ["insert anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Accordion fold sequence is not fully modeled."],
    foldingNotes: ["Documentation implies alternating valley/mountain folds across D1-D6 segments."],
    artworkNotes: ["Usually hidden and product-contacting."],
    productionRisks: ["Incorrect D segment sum causes loose or over-tight insert."],
    usedByTemplates: ["with-built-in-inserts"],
  }),
  contract({
    id: "productMount",
    label: "Product Mount",
    family: "mount-structures",
    sourceDocPartId: "product-mount",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "D1" }, { name: "D2" }, { name: "TL" }, { name: "SR" }],
    outputs: {
      faces: ["mount panel face"],
      structuralCreases: ["mount hinge"],
      anchors: ["mount anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["D1 + D2 must be verified against interior width and material thickness."],
    foldingNotes: ["Mount panels fold inward to create a shelf or cradle."],
    artworkNotes: ["Interior product-contact surface."],
    productionRisks: ["Mount geometry is highly size-dependent."],
    usedByTemplates: ["snap-lock-bottom-carton-with-mount"],
  }),
  contract({
    id: "internalHolder",
    label: "Internal Holder",
    family: "internal-structures",
    sourceDocPartId: "built-in-insert",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "holderDepth" }],
    outputs: {
      faces: ["holder panel face"],
      structuralCreases: ["holder hinge"],
      anchors: ["holder anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Product contact and 3D collision are unverified."],
    foldingNotes: ["Generic internal holder subpart for future insert assemblies."],
    artworkNotes: ["Usually no critical print."],
    productionRisks: ["May crush or misalign product if dimensions are wrong."],
    usedByTemplates: ["with-built-in-inserts", "snap-lock-bottom-carton-with-mount"],
  }),
  contract({
    id: "compartmentGrid",
    label: "Compartment Grid",
    family: "internal-structures",
    sourceDocPartId: "integrated-partition",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }],
    outputs: { geometryPrimitives: ["grid guide line"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Grid cell count and 3D arrangement are not fully modeled."],
    foldingNotes: ["Represents the guide/interlock layout for compartment systems."],
    artworkNotes: ["Interior guide only."],
    productionRisks: ["Incorrect slot/grid position collapses compartments."],
    usedByTemplates: ["carton-with-integrated-partitions"],
  }),
  contract({
    id: "partitionLockSlot",
    label: "Partition Lock Slot",
    family: "internal-structures",
    sourceDocPartId: "integrated-partition",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "slotWidth" }, { name: "slotHeight" }],
    outputs: { geometryPrimitives: ["partition lock slot"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Slot width must account for material thickness and clearance."],
    foldingNotes: ["Receives another partition panel; does not create a crease."],
    artworkNotes: ["Usually hidden."],
    productionRisks: ["Cross-slot fit is tolerance critical."],
    usedByTemplates: ["carton-with-integrated-partitions", "snap-lock-bottom-carton-with-divider"],
  }),
  contract({
    id: "partitionGlueZone",
    label: "Partition Glue Zone",
    family: "internal-structures",
    sourceDocPartId: "integrated-partition",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "glueHeight" }],
    outputs: { geometryPrimitives: ["partition adhesive guide"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Adhesive area depends on product load and board finish."],
    foldingNotes: ["Guides partition adhesive only."],
    artworkNotes: ["No-print zone for partition glue."],
    productionRisks: ["Undersized glue zones can fail in transit."],
    usedByTemplates: ["internal partition variants"],
  }),

  contract({
    id: "trayBody",
    label: "Tray Body",
    family: "skillet-structures",
    sourceDocPartId: "skillet-insert-panel",
    implementationStatus: "partial-experimental",
    inputs: [{ name: "L" }, { name: "W" }],
    outputs: {
      faces: ["tray base face"],
      anchors: ["edge anchors for tray walls"],
    },
    createsFaces: true,
    createsAnchors: true,
    validationRules: ["L and W must be positive.", "Tray base must not self-intersect."],
    warningRules: ["Tray wall/corner assembly is not fully modeled."],
    foldingNotes: ["Base receives side walls and corner tabs."],
    artworkNotes: ["May be visible product-facing surface."],
    productionRisks: ["Wall height and corner tab sequence require prototype checks."],
    usedByTemplates: ["separated-skillet-box"],
  }),
  contract({
    id: "traySideWall",
    label: "Tray Side Wall",
    family: "skillet-structures",
    sourceDocPartId: "skillet-insert-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "wallHeight" }],
    outputs: {
      faces: ["tray side wall face"],
      structuralCreases: ["wall hinge"],
      anchors: ["wall anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Tray corner clearance is unverified."],
    foldingNotes: ["Side wall folds up from tray base."],
    artworkNotes: ["Outside wall may be printable."],
    productionRisks: ["Wall height controls lid fit."],
    usedByTemplates: ["separated-skillet-box"],
  }),
  contract({
    id: "trayCornerTab",
    label: "Tray Corner Tab",
    family: "skillet-structures",
    sourceDocPartId: "skillet-insert-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "tabDepth" }, { name: "tabTaper" }],
    outputs: {
      faces: ["tray corner glue/lock tab"],
      structuralCreases: ["corner tab hinge"],
      anchors: ["corner tab anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Corner tab glue/lock behavior is unverified."],
    foldingNotes: ["Corner tab joins tray walls at the corners."],
    artworkNotes: ["Usually glue/no-print."],
    productionRisks: ["Corner tabs determine tray squareness."],
    usedByTemplates: ["separated-skillet-box"],
  }),
  contract({
    id: "skilletBody",
    label: "Skillet Body",
    family: "skillet-structures",
    sourceDocPartId: "sleeve-body",
    implementationStatus: "partial-experimental",
    inputs: [{ name: "L" }, { name: "W" }, { name: "H" }],
    outputs: {
      faces: ["shallow skillet body face"],
      anchors: ["edge anchors for skillet walls/lid"],
    },
    createsFaces: true,
    createsAnchors: true,
    validationRules: ["L and W must be positive.", "Skillet proportions should be shallow/landscape."],
    warningRules: ["Skillet end geometry is not fully modeled."],
    foldingNotes: ["Base shell for skillet-style cartons."],
    artworkNotes: ["Broad face is usually primary artwork surface."],
    productionRisks: ["Shallow clearances are sensitive to board thickness."],
    usedByTemplates: ["reversible-lid-skillet-carton", "separated-skillet-box"],
  }),
  contract({
    id: "skilletLid",
    label: "Skillet Lid",
    family: "skillet-structures",
    sourceDocPartId: "reversible-lid-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "lidDepth" }],
    outputs: {
      faces: ["skillet lid face"],
      structuralCreases: ["lid hinge"],
      anchors: ["lid anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Lid/base clearance is unverified."],
    foldingNotes: ["Lid rotates over shallow skillet body."],
    artworkNotes: ["Primary visible lid surface."],
    productionRisks: ["Registration mechanism needs prototype validation."],
    usedByTemplates: ["reversible-lid-skillet-carton", "separated-skillet-box"],
  }),
  contract({
    id: "separatedSkilletBase",
    label: "Separated Skillet Base",
    family: "skillet-structures",
    sourceDocPartId: "skillet-insert-panel",
    implementationStatus: "partial-experimental",
    inputs: [{ name: "L" }, { name: "W" }],
    outputs: {
      faces: ["separate base panel"],
      anchors: ["base anchors"],
    },
    createsFaces: true,
    createsAnchors: true,
    validationRules: ["Base dimensions must be positive."],
    warningRules: ["Two-piece lid/base registration is not modeled."],
    foldingNotes: ["Base is one dieline piece of a separated skillet system."],
    artworkNotes: ["May be mostly covered by lid."],
    productionRisks: ["Lid/base registration is unknown from documentation alone."],
    usedByTemplates: ["separated-skillet-box"],
  }),
  contract({
    id: "separatedSkilletLid",
    label: "Separated Skillet Lid",
    family: "skillet-structures",
    sourceDocPartId: "skillet-insert-panel",
    implementationStatus: "partial-experimental",
    inputs: [{ name: "L" }, { name: "W" }],
    outputs: {
      faces: ["separate lid panel"],
      anchors: ["lid anchors"],
    },
    createsFaces: true,
    createsAnchors: true,
    validationRules: ["Lid dimensions must be positive."],
    warningRules: ["Two-piece lid fit is reference-pending."],
    foldingNotes: ["Lid is separate from base and must register when closed."],
    artworkNotes: ["Primary visible display surface."],
    productionRisks: ["Unverified friction/lip mechanism."],
    usedByTemplates: ["separated-skillet-box"],
  }),
  contract({
    id: "skilletSideWall",
    label: "Skillet Side Wall",
    family: "skillet-structures",
    sourceDocPartId: "sleeve-body",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "wallHeight" }],
    outputs: {
      faces: ["skillet side wall face"],
      structuralCreases: ["wall hinge"],
      anchors: ["wall anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Shallow wall clearances are unverified."],
    foldingNotes: ["Side wall folds up from skillet body."],
    artworkNotes: ["Side wall may include secondary branding."],
    productionRisks: ["Small clearance changes affect lid fit."],
    usedByTemplates: ["reversible-lid-skillet-carton", "separated-skillet-box"],
  }),
  contract({
    id: "skilletCornerLock",
    label: "Skillet Corner Lock",
    family: "skillet-structures",
    sourceDocPartId: "skillet-insert-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "lockWidth" }, { name: "lockDepth" }],
    outputs: {
      faces: ["skillet corner lock tab"],
      structuralCreases: ["corner lock hinge"],
      geometryPrimitives: ["lock shoulder score"],
      anchors: ["corner lock anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Locks or glues shallow skillet corners."],
    artworkNotes: ["Usually hidden at the corner."],
    productionRisks: ["Corner lock determines tray/lid squareness."],
    usedByTemplates: ["separated-skillet-box"],
  }),
  contract({
    id: "skilletInsertPanel",
    label: "Skillet Insert Panel",
    family: "skillet-structures",
    sourceDocPartId: "skillet-insert-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "insertDepth" }, { name: "GD" }],
    outputs: {
      faces: ["skillet insert/platform face"],
      structuralCreases: ["insert hinge"],
      anchors: ["insert anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Two-piece insert/platform fit is reference-pending."],
    foldingNotes: ["Insert platform supports product inside separated skillet systems."],
    artworkNotes: ["Usually product-contacting."],
    productionRisks: ["Must match base/lid registration."],
    usedByTemplates: ["separated-skillet-box"],
  }),
  contract({
    id: "skilletSnapSlot",
    label: "Skillet Snap Slot",
    family: "skillet-structures",
    sourceDocPartId: "skillet-insert-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "SL" }, { name: "SW1" }, { name: "SR" }],
    outputs: { geometryPrimitives: ["skillet snap slot"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Receives a snap or registration feature in two-piece skillet systems."],
    artworkNotes: ["Avoid critical print over slot."],
    productionRisks: ["Unknown lid/base registration mechanism."],
    usedByTemplates: ["separated-skillet-box"],
  }),

  contract({
    id: "reversibleLid",
    label: "Reversible Lid",
    family: "reversible-lids",
    sourceDocPartId: "reversible-lid-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "lidDepth" }, { name: "OD1" }, { name: "OD2" }, { name: "EA1" }, { name: "EA2" }],
    outputs: {
      faces: ["reversible lid face"],
      structuralCreases: ["lid-to-body hinge"],
      anchors: ["lid anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Partial-experimental: 180-degree hinge motion is not verified."],
    foldingNotes: ["Lid can rotate open/reversed and close over the front face."],
    artworkNotes: ["Primary visible lid artwork."],
    productionRisks: ["Hinge position and slot engagement are tolerance-critical."],
    usedByTemplates: ["reversible-lid-skillet-carton", "reversible-lid-folding-carton", "separated-skillet-box"],
  }),
  contract({
    id: "reversibleLidHinge",
    label: "Reversible Lid Hinge",
    family: "reversible-lids",
    sourceDocPartId: "reversible-lid-panel",
    implementationStatus: "spec-only",
    requiredAnchors: ["body.top", "lid.base"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "foldAngleDegrees" }],
    outputs: { structuralCreases: ["lid-to-body hinge"] },
    createsStructuralCreases: true,
    validationRules: ["May only be created when both body and lid faces exist."],
    warningRules: ["Spec-only as a standalone part so no fake crease is generated without two real faces."],
    foldingNotes: ["The hinge is created by reversibleLid implementation or a future assembly pass."],
    artworkNotes: ["Avoid heavy ink buildup directly on hinge."],
    productionRisks: ["180-degree open/close fatigue requires material testing."],
    usedByTemplates: ["reversible-lid variants"],
  }),
  contract({
    id: "reversibleLidLockTab",
    label: "Reversible Lid Lock Tab",
    family: "reversible-lids",
    sourceDocPartId: "reversible-lid-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "TL" }, { name: "TD1" }],
    outputs: {
      faces: ["lid lock tab face"],
      structuralCreases: ["tab hinge"],
      geometryPrimitives: ["tab shoulder score"],
      anchors: ["tab anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Tab engages receiver slots when lid is closed."],
    artworkNotes: ["Usually hidden."],
    productionRisks: ["Slot engagement controls opening force."],
    usedByTemplates: ["reversible-lid variants"],
  }),
  contract({
    id: "reversibleLidReceiverSlot",
    label: "Reversible Lid Receiver Slot",
    family: "reversible-lids",
    sourceDocPartId: "reversible-lid-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "SL1" }, { name: "SL2" }, { name: "SW2" }, { name: "SR2" }],
    outputs: { geometryPrimitives: ["receiver slot"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: [clearanceWarning],
    foldingNotes: ["Receives inner lock tab; geometry-only."],
    artworkNotes: ["Avoid important artwork over receiver slot."],
    productionRisks: ["Slot position is critical for lid registration."],
    usedByTemplates: ["reversible-lid variants"],
  }),
  contract({
    id: "lidInsertPanel",
    label: "Lid Insert Panel",
    family: "reversible-lids",
    sourceDocPartId: "reversible-lid-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "insertDepth" }],
    outputs: {
      faces: ["inner insert panel"],
      structuralCreases: ["insert hinge"],
      anchors: ["insert panel anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Insert reach to receiver slot is not verified."],
    foldingNotes: ["Folds inward from lid to engage slots."],
    artworkNotes: ["Usually interior/no primary artwork."],
    productionRisks: ["Wrong insert depth prevents secure closure."],
    usedByTemplates: ["reversible-lid variants"],
  }),

  contract({
    id: "gussetRoofPanel",
    label: "Gusset Roof Panel",
    family: "gusset-structures",
    sourceDocPartId: "gusset-roof-panel",
    implementationStatus: "spec-only",
    requiredAnchors: ["front.top", "back.top", "sideA.top", "sideB.top"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "BFW" }, { name: "TFW" }, { name: "OD" }, { name: "GFW" }],
    outputs: {
      faces: ["front/back roof slopes", "triangular gussets", "ridge closure"],
      structuralCreases: ["roof hinges", "triangle folds", "ridge crease"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    validationRules: ["Roof angle and triangular gusset dimensions must be solved as a complete assembly."],
    warningRules: ["Spec-only because documentation flags roof geometry as expert/high-risk."],
    foldingNotes: ["Two sloped panels meet at a ridge with triangular side gussets."],
    artworkNotes: ["Roof artwork crosses angled fold geometry."],
    productionRisks: ["1mm error can create gaps or overlaps at ridge."],
    usedByTemplates: ["gusset-roof-carton-with-tear-strip"],
  }),
  contract({
    id: "gussetTrianglePanel",
    label: "Gusset Triangle Panel",
    family: "gusset-structures",
    sourceDocPartId: "gusset-roof-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "triangleDepth" }],
    outputs: {
      faces: ["triangular gusset face"],
      structuralCreases: ["triangle base hinge"],
      anchors: ["triangle anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Partial-experimental: true roof angle is not solved."],
    foldingNotes: ["Triangular gusset fills side gap between roof slopes."],
    artworkNotes: ["Usually small angled corner surface."],
    productionRisks: ["Triangle dimensions are roof-angle dependent."],
    usedByTemplates: ["gusset-roof-carton-with-tear-strip", "gusset-cover-crash-bottom-carton"],
  }),
  contract({
    id: "gussetCover",
    label: "Gusset Cover",
    family: "gusset-structures",
    sourceDocPartId: "gusset-cover-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "TFW" }, { name: "FW" }, { name: "FR" }],
    outputs: {
      faces: ["main gusset cover face"],
      structuralCreases: ["cover hinge"],
      anchors: ["cover anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Partial-experimental: corner gusset side/diagonal layout needs verification."],
    foldingNotes: ["Main cover works with side panels and diagonal gusset folds."],
    artworkNotes: ["Visible cover artwork may cross reinforced corner folds."],
    productionRisks: ["Gusset cover assembly is usually machine-sensitive."],
    usedByTemplates: ["gusset-cover-crash-bottom-carton"],
  }),
  contract({
    id: "gussetSidePanel",
    label: "Gusset Side Panel",
    family: "gusset-structures",
    sourceDocPartId: "gusset-cover-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "sideDepth" }],
    outputs: {
      faces: ["gusset side panel face"],
      structuralCreases: ["side panel hinge"],
      anchors: ["side panel anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsAnchors: true,
    validationRules: faceHingeRules,
    warningRules: ["Side panel depth must be checked against cover and box width."],
    foldingNotes: ["Side panel reinforces gusset cover corners."],
    artworkNotes: ["Usually side/interior print."],
    productionRisks: ["Wrong depth causes corner gaps."],
    usedByTemplates: ["gusset-cover-crash-bottom-carton"],
  }),
  contract({
    id: "gussetDiagonalScore",
    label: "Gusset Diagonal Score",
    family: "gusset-structures",
    sourceDocPartId: "gusset-cover-panel",
    implementationStatus: "partial-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }, { name: "FR" }],
    outputs: { geometryPrimitives: ["diagonal gusset score guide"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Partial-experimental: only a guide unless it connects two modeled foldable faces."],
    foldingNotes: ["Diagonal fold lines are structural only when connecting real subfaces."],
    artworkNotes: ["Render as score/fold guide layer."],
    productionRisks: ["Incorrect diagonal placement creates visible gaps."],
    usedByTemplates: ["gusset-roof-carton-with-tear-strip", "gusset-cover-crash-bottom-carton"],
  }),
  contract({
    id: "roofRidgeCrease",
    label: "Roof Ridge Crease",
    family: "gusset-structures",
    sourceDocPartId: "gusset-roof-panel",
    implementationStatus: "spec-only",
    requiredAnchors: ["frontRoof.ridge", "backRoof.ridge"],
    allowedAttachTargets: ["anchor:custom"],
    inputs: [{ name: "roofAngle" }],
    outputs: { structuralCreases: ["ridge hinge between roof faces"] },
    createsStructuralCreases: true,
    validationRules: ["May only be created when both roof slope faces exist."],
    warningRules: ["Spec-only as a standalone part to avoid fake crease generation."],
    foldingNotes: ["Ridge crease joins two real foldable roof faces."],
    artworkNotes: ["Artwork crossing ridge needs distortion allowance."],
    productionRisks: ["Roof ridge position is determined by full roof geometry."],
    usedByTemplates: ["gusset-roof-carton-with-tear-strip"],
  }),

  contract({
    id: "scoreGuide",
    label: "Score Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "verificationRules.score-lines",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any", "face"],
    inputs: [{ name: "offset" }, { name: "length" }],
    outputs: { geometryPrimitives: ["score guide line"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Warn when guide is used where a structural hinge was expected."],
    foldingNotes: ["Internal scores influence folding but do not connect two faces in the graph."],
    artworkNotes: ["Render as score/fold guide color, not cut."],
    productionRisks: ["Incorrect score depth can crack or under-fold board."],
    usedByTemplates: ["all advanced closure assemblies"],
  }),
  contract({
    id: "glueZoneGuide",
    label: "Glue Zone Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "side-glue-tab",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }],
    outputs: { geometryPrimitives: ["glue zone polygon"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Warn when glue zone leaves little adhesive area."],
    foldingNotes: ["Glue zones guide factory adhesive placement only."],
    artworkNotes: ["No print content in glue zones."],
    productionRisks: ["Undersized glue zones can fail under load."],
    usedByTemplates: ["all glued carton bodies"],
  }),
  contract({
    id: "safeAreaGuide",
    label: "Safe Area Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "verificationRules.safe-margins",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }],
    outputs: { geometryPrimitives: ["safe area rectangle"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Warn when inset collapses the guide."],
    foldingNotes: ["Safe areas do not affect folding."],
    artworkNotes: ["Keep critical artwork inside safe area."],
    productionRisks: ["Ignoring safe area can trim important artwork."],
    usedByTemplates: ["all printable templates"],
  }),
  contract({
    id: "bleedGuide",
    label: "Bleed Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "body-strip",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "bleed" }],
    outputs: { geometryPrimitives: ["bleed rectangle"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Warn when bleed is below common 3mm carton artwork practice."],
    foldingNotes: ["Bleed guides do not fold and do not affect structure."],
    artworkNotes: ["Extend background artwork to bleed guide."],
    productionRisks: ["Insufficient bleed risks white edges after trimming."],
    usedByTemplates: ["all printable templates"],
  }),
  contract({
    id: "internalScoreGuide",
    label: "Internal Score Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "verificationRules.score-lines",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }],
    outputs: { geometryPrimitives: ["internal score guide"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Guide only; future assembly must promote real face hinges separately."],
    foldingNotes: ["Score guide does not create a graph edge."],
    artworkNotes: ["Render on score/guide layer."],
    productionRisks: ["Score depth and direction need die specification."],
    usedByTemplates: ["all advanced internal/closure assemblies"],
  }),
  contract({
    id: "noPrintZoneGuide",
    label: "No-Print Zone Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "globalPartFamilies.guide-print-helpers",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "zoneHeight" }],
    outputs: { geometryPrimitives: ["no-print zone"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Guide only; no structural output."],
    foldingNotes: ["No-print guides do not affect folding."],
    artworkNotes: ["Keep ink and critical art out of the marked zone."],
    productionRisks: ["Incorrect no-print markings can reduce glue strength."],
    usedByTemplates: ["all glued/film/locking variants"],
  }),
  contract({
    id: "filmGlueZoneGuide",
    label: "Film Glue Zone Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "window-cutout",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "zoneHeight" }],
    outputs: { geometryPrimitives: ["window film glue zone"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Film adhesive area depends on substrate and window size."],
    foldingNotes: ["Film glue zone is a print/manufacturing helper only."],
    artworkNotes: ["No critical art or ink buildup in film adhesive zone."],
    productionRisks: ["Film adhesion must be specified and tested."],
    usedByTemplates: ["window variants"],
  }),
  contract({
    id: "windowFilmPatchGuide",
    label: "Window Film Patch Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "window-cutout",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "patchWidth" }, { name: "patchHeight" }],
    outputs: { geometryPrimitives: ["film patch guide"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Film patch overlap should be specified by converter."],
    foldingNotes: ["Film patch is not a cut and not a crease."],
    artworkNotes: ["Shows transparent film footprint on the inside face."],
    productionRisks: ["Undersized film patch can peel or leak."],
    usedByTemplates: ["window variants"],
  }),
  contract({
    id: "barcodeSafeZoneGuide",
    label: "Barcode Safe Zone Guide",
    family: "guide-print-helpers",
    sourceDocPartId: "globalPartFamilies.guide-print-helpers",
    implementationStatus: "implemented-experimental",
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "zoneWidth" }, { name: "zoneHeight" }],
    outputs: { geometryPrimitives: ["barcode safe zone"] },
    createsGeometryPrimitives: true,
    validationRules: primitiveOnlyRules,
    warningRules: ["Barcode placement must avoid folds, cuts, and glue zones."],
    foldingNotes: ["Safe zone has no structural effect."],
    artworkNotes: ["Reserve quiet zone and avoid score/cut overlap."],
    productionRisks: ["Bad barcode placement can fail scanning."],
    usedByTemplates: ["bottom panels", "retail cartons"],
  }),
] satisfies V2PartContract[];

export const foldingBoxPartContractById = new Map(foldingBoxPartContracts.map((item) => [item.id, item]));

export function getFoldingBoxPartContract(id: string): V2PartContract {
  const found = foldingBoxPartContractById.get(id);
  if (!found) {
    throw new Error(`Unknown V2 folding box part contract: ${id}`);
  }
  return found;
}
