import type { V2PartContract } from "./types";

function contract(definition: V2PartContract): V2PartContract {
  return { ...definition, productionReady: false };
}

export const foldingBoxPartContracts = [
  contract({
    id: "standardBodyStrip",
    label: "Standard Body Strip",
    family: "body-systems",
    sourceDocPartId: "body-strip",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: [],
    allowedAttachTargets: [],
    inputs: [
      { name: "L", label: "Length", unit: "mm", required: true },
      { name: "W", label: "Width", unit: "mm", required: true },
      { name: "H", label: "Height", unit: "mm", required: true },
      { name: "topAllowance", label: "Top part allowance", unit: "mm" },
      { name: "bottomAllowance", label: "Bottom part allowance", unit: "mm" },
    ],
    outputs: {
      faces: ["back panel", "side B panel", "front panel", "side A panel"],
      structuralCreases: ["vertical face-to-face corner hinges"],
      anchors: ["top, bottom, left, and right anchors for every body panel"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: false,
    createsAnchors: true,
    validationRules: ["L, W, and H must be positive.", "Panel widths must be finite.", "Corner hinges connect real adjacent faces."],
    warningRules: ["Warn when W > L because the documentation defines L as the longer horizontal dimension."],
    foldingNotes: ["Flat layout follows the documentation convention: back, side-B, front, side-A, with glue seam supplied by a separate part."],
    artworkNotes: ["Body panels are printable. Bleed and safe areas are separate guide parts."],
    productionRisks: ["Board grain and inner/outer dimension compensation still require production verification."],
    usedByTemplates: ["reverseTuckEnd", "straightTuckEnd", "with-circular-hang-hole", "with-hang-tab", "with-locking-tab-on-top-and-bottom"],
  }),
  contract({
    id: "sleeveBody",
    label: "Sleeve Body",
    family: "body-systems",
    sourceDocPartId: "sleeve-body",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: [],
    allowedAttachTargets: [],
    inputs: [{ name: "L", required: true }, { name: "H", required: true }, { name: "GFW" }],
    outputs: {
      faces: ["back sleeve panel", "front sleeve panel"],
      structuralCreases: ["front/back sleeve hinge"],
      anchors: ["edge anchors for sleeve panels"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: false,
    createsAnchors: true,
    validationRules: ["L and H must be positive.", "Sleeve layouts should be landscape for skillet-like uses."],
    warningRules: ["Warn when sleeve use is not landscape-oriented."],
    foldingNotes: ["Sleeve folds into a collapsed two-panel shell before end closures are added."],
    artworkNotes: ["Front and back sleeve panels are printable."],
    productionRisks: ["End closure compatibility for skillet bodies is not verified."],
    usedByTemplates: ["reversible-lid-skillet-carton", "separated-skillet-box"],
  }),
  contract({
    id: "sideGlueSeamTab",
    label: "Side Glue Seam Tab",
    family: "glue-systems",
    sourceDocPartId: "side-glue-tab",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:left", "anchor:right"],
    inputs: [{ name: "GFW", label: "Glue flap width", unit: "mm", required: true }],
    outputs: {
      faces: ["glue seam face"],
      structuralCreases: ["glue seam hinge"],
      geometryPrimitives: ["glue zone guide"],
      anchors: ["edge anchors for glue seam face"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["GFW must be positive and normally between 10mm and 20mm.", "Glue zone is a primitive, not a crease."],
    warningRules: ["Warn outside typical glue width range."],
    foldingNotes: ["Glue tab is factory glued last to close the carton tube."],
    artworkNotes: ["Mark as no-print glue zone."],
    productionRisks: ["Adhesive width and dwell time must be verified on the production line."],
    usedByTemplates: ["all"],
  }),
  contract({
    id: "relievedGlueSeamTab",
    label: "Relieved Glue Seam Tab",
    family: "glue-systems",
    sourceDocPartId: "side-glue-tab",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:left", "anchor:right"],
    inputs: [{ name: "GFW", required: true }, { name: "reliefDepth" }, { name: "reliefInset" }],
    outputs: {
      faces: ["glue seam face with relieved corners"],
      structuralCreases: ["glue seam hinge"],
      geometryPrimitives: ["glue zone guide", "corner relief cut guides"],
      anchors: ["edge anchors for glue seam face"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Relief must not collapse the glue tab.", "Relief cuts remain GeometryPrimitive objects."],
    warningRules: ["Warn when relief is large relative to glue width."],
    foldingNotes: ["Relieved corners reduce interference at top and bottom closure folds."],
    artworkNotes: ["Relieved glue zones remain no-print adhesive areas."],
    productionRisks: ["Relief can reduce glue area if oversized."],
    usedByTemplates: ["all advanced seam variants"],
  }),
  contract({
    id: "reverseTuckClosureFlap",
    label: "Reverse Tuck Closure Flap",
    family: "top-closures",
    sourceDocPartId: "reverse-tuck-flap",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TFR" }, { name: "DFW" }],
    outputs: {
      faces: ["tuck closure flap face"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["geometry-only lock notch cut guides"],
      anchors: ["edge anchors for tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["TFW must be positive.", "Base edge width must equal attach anchor.", "Lock notches are GeometryPrimitive objects."],
    warningRules: ["Warn when TFW is unusually short or long compared with the anchor width."],
    foldingNotes: ["Dust flaps fold first, then the tuck flap folds inward and tucks behind them."],
    artworkNotes: ["Tuck flap exterior is printable and often visible when the box opens."],
    productionRisks: ["Short flaps do not lock; long flaps buckle."],
    usedByTemplates: ["reverseTuckEnd", "autoLockBottom", "snapLockBottom", "with-circular-hang-hole"],
  }),
  contract({
    id: "straightTuckClosureFlap",
    label: "Straight Tuck Closure Flap",
    family: "top-closures",
    sourceDocPartId: "straight-tuck-flap",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TFR" }, { name: "DFW" }],
    outputs: {
      faces: ["straight tuck closure flap face"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["geometry-only lock notch cut guides"],
      anchors: ["edge anchors for straight tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Same geometry validation as reverse tuck.", "Template-level owner panel decides straight vs reverse orientation."],
    warningRules: ["Warn when closure proportion is outside common packaging ranges."],
    foldingNotes: ["Both ends tuck from the same direction in straight tuck templates."],
    artworkNotes: ["Preferred for consistent automated loading direction."],
    productionRisks: ["Straight tuck can create asymmetric finished appearance."],
    usedByTemplates: ["straightTuckEnd"],
  }),
  contract({
    id: "fullWidthTuckClosureFlap",
    label: "Full Width Tuck Closure Flap",
    family: "top-closures",
    sourceDocPartId: "reverse-tuck-flap",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TFR" }, { name: "lipScoreOffset" }],
    outputs: {
      faces: ["full-width tuck closure face"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["geometry-only lip score guide"],
      anchors: ["edge anchors for full-width tuck flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Base edge must equal attach anchor.", "Lip score is never a structural crease."],
    warningRules: ["Warn on wide anchors because leading-edge stiffness must be verified."],
    foldingNotes: ["Acts as a full-width insert flap and can receive display or lock subparts later."],
    artworkNotes: ["Full-width flap can carry branding or instructions."],
    productionRisks: ["Large full-width flaps need die and stiffness checks."],
    usedByTemplates: ["with-circular-hang-hole", "with-hang-tab", "tuck-end-folding-carton"],
  }),
  contract({
    id: "lockingLipClosureFlap",
    label: "Locking Lip Closure Flap",
    family: "top-closures",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "TFW", required: true }, { name: "TL", required: true }, { name: "TD1", required: true }, { name: "TR" }],
    outputs: {
      faces: ["locking flap with integrated tab"],
      structuralCreases: ["body-to-flap hinge"],
      geometryPrimitives: ["geometry-only tab shoulder score"],
      anchors: ["edge anchors for lock flap and tab"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["TL must leave side margins.", "TD1 must be positive.", "Receiving slot is a separate geometry-only part."],
    warningRules: ["Warn when tab-to-slot fit is reference pending."],
    foldingNotes: ["Tab bends into a receiving slot after dust flaps fold inward."],
    artworkNotes: ["Slot position should avoid primary branding areas."],
    productionRisks: ["Slots too tight tear paper; slots too loose do not lock."],
    usedByTemplates: ["with-locking-tab-on-top-and-bottom", "carton-with-three-windows"],
  }),
  contract({
    id: "standardDustFlap",
    label: "Standard Dust Flap",
    family: "dust-flaps",
    sourceDocPartId: "dust-flap",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "DFW", required: true }],
    outputs: {
      faces: ["rectangular dust flap face"],
      structuralCreases: ["side-panel-to-dust-flap hinge"],
      anchors: ["edge anchors for dust flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: false,
    createsAnchors: true,
    validationRules: ["DFW must be positive.", "DFW should not exceed half the box width."],
    warningRules: ["Warn when DFW approaches or exceeds half the anchor width."],
    foldingNotes: ["Dust flaps fold inward before main closure panels."],
    artworkNotes: ["Usually interior and unprinted."],
    productionRisks: ["Exact half-width dust flaps can jam."],
    usedByTemplates: ["reverseTuckEnd", "straightTuckEnd", "with-circular-hang-hole", "with-hang-tab"],
  }),
  contract({
    id: "trapezoidDustFlap",
    label: "Trapezoid Dust Flap",
    family: "dust-flaps",
    sourceDocPartId: "dust-flap",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top", "anchor:bottom"],
    inputs: [{ name: "DFW", required: true }, { name: "taper" }],
    outputs: {
      faces: ["trapezoidal dust flap face"],
      structuralCreases: ["side-panel-to-dust-flap hinge"],
      anchors: ["edge anchors for dust flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: false,
    createsAnchors: true,
    validationRules: ["Taper must not collapse the free edge.", "Base edge must match attach anchor."],
    warningRules: ["Warn when taper is large relative to anchor width."],
    foldingNotes: ["Trapezoid dust flaps reduce side interference during closure insertion."],
    artworkNotes: ["Interior support surface; usually no artwork."],
    productionRisks: ["Too much taper reduces dust sealing."],
    usedByTemplates: ["decorative tuck-end variants", "locking tab variants"],
  }),
  contract({
    id: "angledBottomDustFlap",
    label: "Angled Bottom Dust Flap",
    family: "dust-flaps",
    sourceDocPartId: "dust-flap",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "DFW", required: true }, { name: "startInset" }, { name: "endInset" }],
    outputs: {
      faces: ["angled bottom dust flap face"],
      structuralCreases: ["bottom side-panel hinge"],
      anchors: ["edge anchors for bottom dust flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: false,
    createsAnchors: true,
    validationRules: ["Base edge must match bottom attach anchor.", "Insets must leave positive free edge."],
    warningRules: ["Warn when bottom dust flap may interfere with lock bottom parts."],
    foldingNotes: ["Bottom dust flaps fold before bottom lock or snap lock flaps."],
    artworkNotes: ["Usually an interior bottom surface."],
    productionRisks: ["Bottom closure interference must be checked physically."],
    usedByTemplates: ["snap-lock-bottom variants", "tuck-end-folding-carton"],
  }),
  contract({
    id: "bottomLockFlap",
    label: "Bottom Lock Flap",
    family: "bottom-closures",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "bodyDepth", required: true }, { name: "tongueDepth" }, { name: "tongueWidth" }],
    outputs: {
      faces: ["bottom lock flap with tongue"],
      structuralCreases: ["bottom body-to-lock-flap hinge"],
      geometryPrimitives: ["geometry-only tongue shoulder score"],
      anchors: ["edge anchors for lock flap"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Tongue width must be less than flap width.", "Tongue score is not a structural crease."],
    warningRules: ["Warn because full snap-lock bottom assembly is still spec-only."],
    foldingNotes: ["Represents one Lego piece of the snap-lock bottom; complete interlock comes later."],
    artworkNotes: ["Bottom exterior can carry barcode or small production marks."],
    productionRisks: ["Tongue and slot clearances are material-thickness sensitive."],
    usedByTemplates: ["snap-lock-bottom variants"],
  }),
  contract({
    id: "circularCutout",
    label: "Circular Cutout",
    family: "cutouts",
    sourceDocPartId: "circular-hang-hole",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "OD" }, { name: "radius" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["circle cutout"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Circle must stay inside target face.", "Hole keeps margin from cut edges."],
    warningRules: ["Warn when hole diameter is outside typical peg-hook range."],
    foldingNotes: ["Cutout remains a hole in the assembled display panel."],
    artworkNotes: ["Keep critical artwork away from punched hole."],
    productionRisks: ["Off-center hang holes make products tilt on pegs."],
    usedByTemplates: ["with-circular-hang-hole"],
  }),
  contract({
    id: "roundedSlotCutout",
    label: "Rounded Slot Cutout",
    family: "cutouts",
    sourceDocPartId: "locking-lip-flap",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "width", required: true }, { name: "height", required: true }, { name: "radius" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["rounded slot cutout"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Slots are GeometryPrimitive only.", "Slot must not overlap folds or glue zones."],
    warningRules: ["Warn because tab fit is reference-pending."],
    foldingNotes: ["Receives a locking tab or snap tongue."],
    artworkNotes: ["Avoid primary artwork over lock slots."],
    productionRisks: ["Slot clearance controls assembly force."],
    usedByTemplates: ["with-locking-tab-on-top-and-bottom", "snap-lock-bottom variants"],
  }),
  contract({
    id: "euroSlotCutout",
    label: "Euro Slot Cutout",
    family: "cutouts",
    sourceDocPartId: "hang-tab",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "SL", required: true }, { name: "SW", required: true }, { name: "FR" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["euro slot cutout"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Euro slot stays inside tab face.", "Slot keeps margin from tab edges."],
    warningRules: ["Warn when slot is large relative to tab width."],
    foldingNotes: ["Slot is punched through reinforced display tab layers."],
    artworkNotes: ["Peg-display artwork should account for the slot."],
    productionRisks: ["Slot position relative to fold crease is critical."],
    usedByTemplates: ["with-hang-tab"],
  }),
  contract({
    id: "windowCutout",
    label: "Window Cutout",
    family: "cutouts",
    sourceDocPartId: "window-cutout",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "WL", required: true }, { name: "WH", required: true }, { name: "WR" }, { name: "margin" }],
    outputs: { geometryPrimitives: ["rounded rectangle window cutout"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Window must stay within panel and avoid folds/glue.", "Corner radius must be finite."],
    warningRules: ["Warn when window removes too much panel area."],
    foldingNotes: ["Window is cut before folding and keeps shape in 3D."],
    artworkNotes: ["Mark clear film zone and keep artwork margin around window."],
    productionRisks: ["Window weakens panels near creases; film adhesion must be specified."],
    usedByTemplates: ["carton-with-three-windows", "with-circular-hang-hole-and-window", "with-handle-and-window"],
  }),
  contract({
    id: "reliefNotch",
    label: "Relief Notch",
    family: "cutouts",
    sourceDocPartId: "unknownsAndNeedsManualReview.corner-relief-notches",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any"],
    inputs: [{ name: "width", required: true }, { name: "depth", required: true }, { name: "position" }],
    outputs: { geometryPrimitives: ["relief notch cut path"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Relief notches are cut primitives only.", "Notch points must be finite."],
    warningRules: ["Warn because exact notch style is not exposed as a CefBox parameter."],
    foldingNotes: ["Relief reduces cracking and interference where folds meet."],
    artworkNotes: ["Avoid artwork-critical details at relief cuts."],
    productionRisks: ["Relief radius and shape require die verification."],
    usedByTemplates: ["all folding cartons as optional relief"],
  }),
  contract({
    id: "hangPanel",
    label: "Hang Panel",
    family: "hang-display",
    sourceDocPartId: "circular-hang-hole",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "HL", required: true }],
    outputs: {
      faces: ["rectangular hang panel extension"],
      structuralCreases: ["tuck/hang panel hinge"],
      anchors: ["edge anchors for hang panel"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: false,
    createsAnchors: true,
    validationRules: ["Hang panel height must be positive.", "Base edge must equal attach anchor."],
    warningRules: ["Warn because double-layer reinforcement is template-level."],
    foldingNotes: ["Hang panel extension folds with or above the tuck assembly."],
    artworkNotes: ["Highly visible peg-display print surface."],
    productionRisks: ["Single-layer hang panels may tear under product weight."],
    usedByTemplates: ["with-circular-hang-hole"],
  }),
  contract({
    id: "hangTab",
    label: "Folded Hang Tab",
    family: "hang-display",
    sourceDocPartId: "hang-tab",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:top"],
    inputs: [{ name: "TW", required: true }, { name: "SAL", required: true }, { name: "SL" }, { name: "SW" }, { name: "FR" }],
    outputs: {
      faces: ["inner tab half", "outer tab half"],
      structuralCreases: ["tab attachment hinge", "tab midpoint fold hinge"],
      geometryPrimitives: ["euro slot cutout"],
      anchors: ["edge anchors for tab halves"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["TW must be wide enough for slot margins.", "Midpoint fold is a structural face-to-face hinge."],
    warningRules: ["Warn because display-load behavior needs prototype validation."],
    foldingNotes: ["Outer half folds 180 degrees onto inner half and is glued for double thickness."],
    artworkNotes: ["Both faces are visible in peg display workflows."],
    productionRisks: ["Tab centering and slot position determine hanging stability."],
    usedByTemplates: ["with-hang-tab"],
  }),
  contract({
    id: "scoreGuide",
    label: "Score Guide",
    family: "artwork-guides",
    sourceDocPartId: "verificationRules.score-lines",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachTo"],
    allowedAttachTargets: ["anchor:any", "face"],
    inputs: [{ name: "offset" }, { name: "length" }],
    outputs: { geometryPrimitives: ["score guide line"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Score guides are GeometryPrimitive only."],
    warningRules: ["Warn when guide is used where a structural hinge was expected."],
    foldingNotes: ["Internal scores influence folding but do not connect two faces in the graph."],
    artworkNotes: ["Render as score/fold guide color, not cut."],
    productionRisks: ["Incorrect score depth can crack or under-fold board."],
    usedByTemplates: ["all advanced closure assemblies"],
  }),
  contract({
    id: "glueZoneGuide",
    label: "Glue Zone Guide",
    family: "artwork-guides",
    sourceDocPartId: "side-glue-tab",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }],
    outputs: { geometryPrimitives: ["glue zone polygon"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Glue zone guide must stay inside its target face."],
    warningRules: ["Warn when glue zone leaves little adhesive area."],
    foldingNotes: ["Glue zones guide factory adhesive placement only."],
    artworkNotes: ["No print content in glue zones."],
    productionRisks: ["Undersized glue zones can fail under load."],
    usedByTemplates: ["all glued carton bodies"],
  }),
  contract({
    id: "safeAreaGuide",
    label: "Safe Area Guide",
    family: "artwork-guides",
    sourceDocPartId: "verificationRules.safe-margins",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "inset" }],
    outputs: { geometryPrimitives: ["safe area rectangle"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Safe area guide must stay inside target face."],
    warningRules: ["Warn when inset collapses the guide."],
    foldingNotes: ["Safe areas do not affect folding."],
    artworkNotes: ["Keep critical artwork inside safe area."],
    productionRisks: ["Ignoring safe area can trim important artwork."],
    usedByTemplates: ["all printable templates"],
  }),
  contract({
    id: "bleedGuide",
    label: "Bleed Guide",
    family: "artwork-guides",
    sourceDocPartId: "body-strip",
    implementationStatus: "implemented-experimental",
    productionReady: false,
    requiredAnchors: ["attachToFace"],
    allowedAttachTargets: ["face"],
    inputs: [{ name: "bleed" }],
    outputs: { geometryPrimitives: ["bleed rectangle"] },
    createsFaces: false,
    createsStructuralCreases: false,
    createsGeometryPrimitives: true,
    createsAnchors: false,
    validationRules: ["Bleed must be positive and finite."],
    warningRules: ["Warn when bleed is below common 3mm carton artwork practice."],
    foldingNotes: ["Bleed guides do not fold and do not affect structure."],
    artworkNotes: ["Extend background artwork to bleed guide."],
    productionRisks: ["Insufficient bleed risks white edges after trimming."],
    usedByTemplates: ["all printable templates"],
  }),
  contract({
    id: "snapLockBottomPanel",
    label: "Snap-Lock Bottom Panel Assembly",
    family: "bottom-closures",
    sourceDocPartId: "snap-lock-bottom-panel",
    implementationStatus: "spec-only",
    productionReady: false,
    requiredAnchors: ["front.bottom", "back.bottom", "sideA.bottom", "sideB.bottom"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "DFW" }, { name: "tongueWidth" }, { name: "slotWidth" }],
    outputs: {
      faces: ["major tongue flap", "major receiver flap", "minor side flaps"],
      structuralCreases: ["four bottom face-to-face hinges"],
      geometryPrimitives: ["lock slot cutout"],
      anchors: ["bottom flap anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Tongue/slot clearance must be material-thickness aware.", "Slot remains GeometryPrimitive only."],
    warningRules: ["Spec-only until snap-lock interlock can be reference/prototype validated."],
    foldingNotes: ["Minor flaps fold first, receiver folds next, tongue flap locks last."],
    artworkNotes: ["Bottom exterior slot may affect barcode placement."],
    productionRisks: ["Interlock clearances determine assembly force and load capacity."],
    usedByTemplates: ["snapLockBottom", "centered-tuck-end-carton", "tuck-end-folding-carton"],
  }),
  contract({
    id: "autoLockBottomPanel",
    label: "Auto-Lock Bottom Panel Assembly",
    family: "bottom-closures",
    sourceDocPartId: "auto-lock-bottom-panel",
    implementationStatus: "spec-only",
    productionReady: false,
    requiredAnchors: ["front.bottom", "back.bottom", "sideA.bottom", "sideB.bottom"],
    allowedAttachTargets: ["anchor:bottom"],
    inputs: [{ name: "DFW" }, { name: "GFW" }, { name: "overlap" }],
    outputs: {
      faces: ["major flaps", "minor flaps", "auto-lock glue panel"],
      structuralCreases: ["bottom hinges"],
      geometryPrimitives: ["diagonal score guides", "pre-glue zone"],
      anchors: ["bottom assembly anchors"],
    },
    createsFaces: true,
    createsStructuralCreases: true,
    createsGeometryPrimitives: true,
    createsAnchors: true,
    validationRules: ["Diagonal scores must remain GeometryPrimitive guides.", "Pre-glue zone remains a guide primitive."],
    warningRules: ["Spec-only because diagonal score geometry requires reference/prototype validation."],
    foldingNotes: ["Factory pre-glued bottom springs open when the carton tube is erected."],
    artworkNotes: ["Major bottom surfaces can carry barcode and production marks."],
    productionRisks: ["Diagonal score angle is critical to flat collapse and pop-open behavior."],
    usedByTemplates: ["autoLockBottom", "with-handle", "auto-lock-bottom-carton-with-tab-closure"],
  }),
] satisfies V2PartContract[];

export const foldingBoxPartContractById = new Map(foldingBoxPartContracts.map((item) => [item.id, item]));

export function getFoldingBoxPartContract(id: string): V2PartContract {
  const found = foldingBoxPartContractById.get(id);
  if (!found) {
    throw new Error(`Unknown V2 folding box part contract: ${id}`);
  }
  return found;
}
